# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

# Text to speech
tts:
  - platform: google_translate

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
template: !include template.yaml
sensor: !include sensors.yaml
binary_sensor: !include binary_sensor.yaml
homekit:
fibaro:
python_script:

  # input_number lagrer verdier som trengs ved senere anledninger.
  # De under trengs i effektregulerings-scriptet.
input_number:
  control_output:
    name: "Control Output"
    min: 0
    max: 100
  energy_sum:
    name: "Energy Sum"
    min: 0
    max: 10000000
    step: 0.01
  current_check:
    name: "Current Check"
    min: 0
    max: 120
    step: 1
  remaining_energy_budget:
    name: "Remaining Energy Budget"
    min: 0
    max: 50000
  max_next_power:
    name: "Max next power"
    min: 0
    max: 30000

  # For simulering:
  sum_energiforbruk_simulering:
    name: "Energiforbruk sum"
    min: 0
    max: 10000000
    step: 0.01
  tellevariabel_simulering:
    name: "Tellevariabel Script"
    min: 0
    max: 120
    step: 1
    unit_of_measurement: "Wh"
  gjenstaende_energi_budsjett_simulering:
    name: "Gjenstående energi denne timen"
    min: 0
    max: 50000
    unit_of_measurement: "Wh"
  neste_maksgrense_simulering:
    name: "Maksgrense effekt"
    min: 0
    max: 30000
    unit_of_measurement: "W"
  valgt_timegrense:
    name: "Timegrense"
    min: 0
    max: 20
    mode: box
    unit_of_measurement: "kWh"
  #Antall timer elbil skal lade mellom kl 00 og 06.
  antall_timer_elbil:
    name: "Antall timer elbil skal lade om natta"
    min: 0
    max: 6
    initial: 4
    mode: box
    unit_of_measurement: "h"

  antall_ganger_over_next:
    name: "Antall ganger over max_next_energy"
    min: 0
    max: 100
  varmtvannsbereder_prioritet:
    name: "Bereder prioritet"
    min: 1
    max: 10
    step: 1
  varmtvannsbereder_forrige_prioritet:
    name: "Berederens forrige prioritet"
    min: 1
    max: 10
    step: 1
  varmekabler_prioritet:
    name: "Varmekabler prioritet"
    min: 1
    max: 10
    step: 1
  varmeovn_1_prioritet:
    name: "Varmeovn 1"
    min: 1
    max: 10
    step: 1
  varmeovn_2_prioritet:
    name: "Varmeovn 2"
    min: 1
    max: 10
    step: 1
  varmeovn_3_prioritet:
    name: "Varmeovn 3"
    min: 1
    max: 10
    step: 1
  varmeovn_4_prioritet:
    name: "Varmeovn 4"
    min: 1
    max: 10
    step: 1
  riemann_energi_forbruk_time:
    name: "Energiforbruk i løpet av en time"
    min: 1
    max: 200
    step: 0.01
  na_forbruk_hvert_2_min:
    name: "Verdi av gj. snitt forbruk hvert 2. min"
    min: 0
    max: 30000
    step: 1

  # For simulasjon:
  grense_effektforbruk_simulering:
    name: "Grense effektforbruk [W]"
    min: 0
    max: 14000
    step: 100

input_boolean:
  varmekabler_paa:
    name: "Varmekabler (1500W)"
  varmtvannstank_paa:
    name: "Varmtvannstank (2000W)"
  varmeovn_1_paa:
    name: "Varmeovn 1 (1000W)"
  varmeovn_2_paa:
    name: "Varmeovn 2 (500W)"
  varmeovn_3_paa:
    name: "Varmeovn 3 (500W)"
  varmeovn_4_paa:
    name: "Varmeovn 4 (300W)"
  elbil_lader_paa:
    name: "Elbil lader (7000W)"
  simulere_next:
    name: "Simulere max next energy?"
  # Flagg for å sjekke om varsel om høyt effektforbruk er sendt ut. Tilbakestilles hver time
  varsel_sendt_ut:
    name: "Effektvarsel sendt ut?"

  # Disse sjekker om algoritmen skrudde av enheten.
  algoritme_varmekabler:
  algoritme_varmtvannstank:
  algoritme_varmeovn_1:
  algoritme_varmeovn_2:
  algoritme_varmeovn_3:
  algoritme_varmeovn_4:
  elbil_lader:
